# Hand-written claim overrides and significance lines for the rows cited on figure 10a-anthropic. Edit here, then rebuild EVIDENCE with scripts/build_evidence.py.
CLAIM={
"ST26":"Anthropic's Series H release (May 28 2026) names Jane Street and D.E. Shaw Ventures among the investors; individual amounts are not disclosed.",
"ST41":"Jaan Tallinn told Postimees (Feb 2026) that he is an Anthropic board observer rather than a director.",
"ST49":"Forbes reports that Eric Schmidt's family office, Hillspire, bought 20% of D.E. Shaw & Co.; Schmidt's Forbes profile does not mention Anthropic.",
"ST54":"Anthropic's Series A release names the Center for Emerging Risk Research (now Macroscopic Ventures) as an investor; its Series B release names it again. Amounts undisclosed.",
"ST32":"Forbes (Nov 7 2025, Phoebe Liu) put the Moskovitz–Tuna Anthropic stake at \"an estimated $500 million\".",
"ST33":"Forbes, quoting Cari Tuna: the stake \"was moved into a nonprofit vehicle in early 2025\" to \"dispel any perception of conflict of interest\". The vehicle is not named.",
}
WHY={
"ST26":"Fixes the Series H investor list that the panel and the $965B valuation rest on, and shows the firm-level Jane Street link to the lab whose staff METR names as donors.",
"ST32":"The only published dollar estimate of the donated stake; it is the left bar of the chart and the '$500M' in the title.",
"ST33":"Establishes that the stake was donated in early 2025 and that Tuna gave conflict-of-interest as the reason; the vehicle is unnamed, which is the question the rest of the stakes rows try to close.",
"ST41":"Tallinn, METR's other large early funder through SFF, is an Anthropic board observer by his own account; the figure says 'observer', never 'director'.",
"ST49":"Links Schmidt, a Series A investor and METR supporter through Schmidt Sciences, to D.E. Shaw, whose venture arm joined Series H; the figure uses Forbes' exact 20%.",
"ST54":"CERR/Macroscopic is both an Anthropic Series A and B investor and a funder of Redwood and Longview, two of METR's intermediaries.",
"ST78":"Good Ventures Foundation's own FY2025 Schedule B lists two contributors and one non-cash gift of publicly traded securities; no private stock. So the shares had not reached the 990-PF filer by June 2025.",
"ST79":"The foundation's investment schedules name 406 public issuers and no Anthropic holding; indirect exposure through funds cannot be excluded.",
"ST89":"Coefficient's CEO says the stake was donated and 'not to us', so Coefficient's own entities are out; the recipient is still unnamed.",
"ST90":"Moskovitz says Good Ventures is 'itself a beneficiary' of the coming wave of AI wealth 'via Anthropic', i.e. the giving complex expects to gain when Anthropic gains.",
"ST91":"Forbes says the couple give through Good Ventures Foundation 'plus more in donor-advised funds', which is why the DAF route is on the figure.",
"ST92":"Forbes' 'less than 0.8%' is the only percentage bound found; 0.8% of the $965B Series H valuation is the $7.7B ceiling on the figure.",
"ST93":"Moskovitz's own words that his giving funds METR and Redwood.",
"ST94":"A full-text scan of every IRS e-file received in 2025 and 2026 finds no return naming Anthropic stock held by a Moskovitz or Tuna vehicle; a bounded negative.",
"ST95":"Identifies the family trust that makes the foundation's largest gifts; its holdings are on no public document.",
"ST96":"The NYT's investor-base reporting gives no percentage for any METR-named funder; nothing in the press resolves the stake.",
"ST97":"The WSJ confirms Jane Street's Anthropic position came partly from the FTX estate sale but gives no current share count.",
"ST98":"Tallinn declines to state his Anthropic percentage, so his dashed link is 'undisclosed'.",
"ST99":"Lists the entities through which Moskovitz holds reporting-company shares; none is shown holding Anthropic.",
"ST100":"Good Ventures' public book at June 2025 is concentrated in AI-infrastructure stocks (TSMC, SK Hynix, Broadcom, Vistra, Micron, Vertiv); the endowment is positioned on the same boom as the lab.",
"ST101":"The foundation's investment manager launched an AI hedge fund in March 2025; $4.35B sold to 116 investors by June 2026.",
"ST102":"The manager's reported public book grew from $4.7B to $40.1B in a year, led by Nvidia, Alphabet and Amazon; no Anthropic, which a 13F would not show.",
"ST103":"The sweep of DAF sponsors' closely-held-stock intake that narrows where a private-stock gift could have landed; corrected after audit to note line 11 and the 18 e-files on disk.",
"ST104":"NPT, one of Coefficient's two named DAF partners, took in $1.18B of closely held stock in 19 gifts in the year covering early 2025. Unattributed; a signal, not an identification.",
"ST105":"Coefficient's own page names Good Ventures Foundation, SVCF and NPT as the external funding partners that approve its grants, without naming the account principals.",
"ST106":"NPT's closely-held equity held at year-end rose by $996M in the same year; unattributed.",
"ST107":"SVCF granted NPT $1.59B in 2024 and Constellation $10M; the account family behind Coefficient's grants moved from SVCF to NPT.",
"ST108":"NPT's grants to METR's network (RAND $61.6M, Founders Pledge, FAR, Effective Ventures, Epoch, Longview, Redwood) jump in FY2025; NPT has no METR or ARC line.",
"ST109":"Exact-amount matches prove Coefficient's awards are paid from accounts at SVCF and NPT; 18 matches after audit. Proves the routing, not who owns the accounts.",
"ST110":"Moskovitz: 'Our Anthropic shares are entirely in our foundation - no personal benefit.' His most direct statement; 'foundation' is his word, not a legal entity.",
"ST111":"The thread root names Good Ventures as the funder surging Coefficient's budgets ahead of 'the anticipated wave of new funders'.",
"ST112":"Second statement in four minutes placing all Anthropic holdings 'in the foundation, dedicated to charity'.",
"ST113":"'About $20B more in the foundation … invested in Anthropic as well', double the 990-PF filer's assets, so 'the foundation' covers more than Good Ventures Foundation.",
"ST114":"Open Philanthropy's own page said grants were recommended to 'the Open Philanthropy Project fund, an advised fund of SVCF', naming the DAF account by name.",
"ST115":"The IRS split-interest-trust file has no Moskovitz, Tuna or CTF trust, so the trust route is private and cannot be read.",
"ST116":"NPT paid $50M to Coefficient Giving Advisors and $146.9M in Coefficient-pattern grants in FY2025; the DAF sponsor is a live channel for the giving complex.",
"ST117":"Blue Owl's 2021 S-1 shows the family's private vehicles (Moskovitz Investments LLC, the CTF Trust) and Good Ventures Foundation side by side as holders; a precedent for the foundation holding private units in its own name.",
"ST118":"Moskovitz, in his own words: 'I'm a board observer at Anthropic' and 'in the boardroom in at Anthropic and I know all the players'. Card 3.",
"ST121":"NPT's Schedule B is publicly inspectable on request and must list every contributor above $303M with the asset class, value and date of non-cash gifts; the route that could still settle the sponsor.",
"ST124":"Cari Tuna chairs both Good Ventures Foundation and Coefficient's Board of Managers; Moskovitz is a manager, not chair, which is how card 3 words it.",
"ST125":"VARA's Form ADV shows at least one of its two charitable clients is an LP in the AI fund; which one is not stated.",
"ST127":"The AI fund's co-owner sits on the board of ARC, METR's parent; a join between the endowment's manager and the evaluator's parent.",
"ST133":"Vanguard Charitable's posted Schedule B names no issuer; its largest private-equity line in the window is $130M. Unresolved, not excluded.",
"ST140":"The foundation's $10M FY2024 grant to Open Philanthropy Advisors (now Coefficient Giving Advisors), the line on the Good Ventures node.",
"IV01":"The 2021 Series A: Tallinn led; Moskovitz, Schmidt, McClave and CERR joined. The origin of every equity link on the figure.",
"IV02":"The Series B: Alameda/FTX's ~$500M plus the same early investors; Jane Street later bought the FTX estate's shares.",
"IV05":"The court-supervised FTX estate sale at ~$30 a share, where Jane Street bought 3,332,833 shares for $99,999,988.",
"IV06":"The second estate sale at the same price; fixes the 2024 per-share mark.",
"IV07":"Series E at $61.5B post-money, March 2025, the valuation in force when the stake was donated.",
"IV08":"Series F at $183B, September 2025.",
"IV09":"Series G at $380B, February 2026; D.E. Shaw Ventures appears.",
"IV10":"Series H at $965B, May 2026: the valuation behind the $7.7B ceiling.",
"IV11":"WSJ's reported IPO target of ~$2T; reporting, not a transaction, and labelled so.",
"M75":"METR names 'individuals from Jane Street' as donors, not the firm; the figure keeps that distinction.",
"M120":"Coefficient's grantmakers recommended more than $70M over two years for Redwood, METR's contractor; a recommendation, not a paid grant.",
"M139":"Macroscopic, an Anthropic investor, lists Redwood among its grantees.",
"M140":"Macroscopic lists two Longview programs among its grants; Longview is METR's pooled-fund donor.",
"M141":"Macroscopic holds Apollo Research, another evaluator, as an impact investment.",
"M142":"Macroscopic holds Halcyon Venture Partners, the venture arm beside METR's incubator, as an investment.",
"G14":"METR's own later figure for its Audacious money: 'a bit under $16m' over three years, against the ~$17M announced.",
"TB02":"First Coefficient award to the Tarbell Center; part of the $5.29M on the Tarbell pipe.",
"TB03":"Third Coefficient award to the Tarbell Center.",
"TB04":"Largest Coefficient award to the Tarbell Center.",
"TB05":"SFF's 2024 recommendation for the Tarbell Fellowship, paid via Players Philanthropy Fund; a recommendation, kept separate from awards.",
"TB06":"SFF's 2025 recommendation for the Tarbell Center, including a $200K conditional match.",
"RW31":"METR announced its OpenAI investigation 'with Redwood Research'.",
"RW32":"METR's OpenAI report names a Redwood staff member contracting with METR.",
"RW33":"OpenAI's own technical report names METR and Redwood as the third-party assessors.",
"RW34":"Redwood cross-posted the investigation under Greenblatt's byline.",
"RW36":"Redwood's own post: 'Several staff from Redwood have been subcontracted by METR to work on this investigation', the Anthropic one. Terms undisclosed.",
"RW58":"Search closure: no page names the subcontracted staff or terms; Anthropic's announcement names only METR.",
"J02":"McClave is a Series A and B investor; his BEMC Foundation is not a METR donor on any checked filing.",
"J08":"Schmidt Sciences is a named METR supporter; Schmidt is a Series A investor.",
"B05":"Adam Gleave, FAR AI's CEO, sits on METR's board; FAR AI received $59.3M of Coefficient awards.",
"K01":"METR says it takes no money from AI companies but receives 'significant free tokens' from unnamed frontier companies; unbooked and unquantified.",
"S13":"Joe Benton left Anthropic's alignment team to join METR's incident-investigation staff in September 2026, the month METR began investigating Anthropic.",
}
for k,v in {"TO01":"TIME","TO02":"The Verge","TO03":"MIT Technology Review","TO04":"Lawfare","TO05":"The Guardian","TO06":"the Los Angeles Times"}.items():
    WHY[k]=f"Count behind the {v} chip on the Tarbell branch: Coefficient-funded fellows' AI articles found in the captured window. Counts mix publisher tags and a keyword fallback and windows are partial, so they are not comparable full-year shares."
